export function objectCreater({
  id,
  createdAt,
  paymentDue,
  description,
  paymentTerms,
  clientName,
  clientEmail,
  status,
  senderStreet,
  senderCity,
  senderPostCode,
  senderCountry,
  street,
  city,
  postCode,
  country,
  items,
}) {
  return {
    id,
    createdAt,
    paymentDue,
    description,
    paymentTerms: Number(paymentTerms),
    clientName,
    clientEmail,
    status,
    senderAddress: {
      street: senderStreet,
      city: senderCity,
      postCode: senderPostCode,
      country: senderCountry,
    },
    clientAddress: { street, city, postCode, country },
    items,
    total: items.reduce((acc, item) => acc + item.total, 0),
  };
}
